"""Add cart and payment models

Revision ID: ae9c27854021
Revises: 
Create Date: 2025-05-15 12:44:12.818730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae9c27854021'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # These are the CREATE TABLE commands auto-generated for CartItem and PaymentTransaction
    op.create_table('cart_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='_user_product_uc') # This is from the __table_args__
    )
    op.create_table('payment_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_time', sa.DateTime(), nullable=False),
    sa.Column('mpesa_checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('mpesa_receipt_number', sa.String(length=100), nullable=True),
    sa.Column('mpesa_payload', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # REMOVE or COMMENT OUT the op.alter_column for 'product', 'image_file'
    # op.alter_column('product', 'image_file',
    #            existing_type=sa.VARCHAR(length=20), # Change VARCHAR(20) to match your actual current DB schema if not 20
    #            type_=sa.String(length=100),
    #            nullable=True, # Match existing nullable
    #            existing_comment=None,
    #            existing_nullable=True) # Match existing nullable


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # REMOVE or COMMENT OUT the op.alter_column for 'product', 'image_file' in downgrade
    # op.alter_column('product', 'image_file',
    #            existing_type=sa.String(length=100),
    #            type_=sa.VARCHAR(length=20), # Change VARCHAR(20) to match original schema if not 20
    #            nullable=True, # Match original nullable
    #            existing_comment=None,
    #            existing_nullable=True) # Match original nullable

    op.drop_table('payment_transaction')
    op.drop_table('cart_item')
    # ### end Alembic commands ###